@urlBase = http://localhost:5000

GET {{urlBase}}/students/ HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxNjkwY2E5Y2Y3ZDEzNzAzY2Q2MzYxNCIsImVtYWlsIjoiZW1hZmVybW9uQGdtYWlsLmNvbSIsIl9fdiI6MCwiYWRtaW4iOmZhbHNlLCJuYW1lIjoiRW1hbnVlbCBGZXJuYW5kbyBNb250b3lhIEdvbWV6Iiwic3VybmFtZXMiOiJNb250b3lhIEdvbWV6In0sImlhdCI6MTYzNDQwMTI0NiwiZXhwIjoxNjM0NDA0ODQ2fQ.8XZOcBCMYPalf09ijj_uYyOJX9YGap3i99Qiv0QfgW8
###

GET http://localhost:5000/students/61611d4f4067cb68a43790ae HTTP/1.1
###

POST http://localhost:5000/students HTTP/1.1
content-type: application/json

{
    "dni": 102032,
    "name": "andres ordoñez",
    "age": 34,
    "semester": 3
}
###

DELETE {{urlBase}}/students/6161966804aad3dd4c34c71c

###
PUT http://localhost:5000/students/61611d764067cb68a43790b2
content-type: application/json

{
    "dni": 989898,
    "name": "Juan antonio cardona",
    "age": 17,
    "semester": 1
}
